version: "3.3"
services:
  home-assistant:
    hostname: homeassistant
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.localhost`)"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.homeassistant.entrypoints=http"

networks:
  default:
    external:
      name: traefik_internal
