kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deluge-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deluge-download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
