version: "3.3"
services:
  watchtower:
    hostname: watchtower
    container_name: watchtower
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
