apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prometheus-exporter-homehub
  labels:
    app: prometheus-exporter-homehub
spec:
  schedule: 30 * * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: ghcr.io/davidsbond/homelab:latest
            name: prometheus-exporter-homehub
            command:
            - /bin/prometheus-exporter-homehub
            env:
            - name: TRACER_HOST
              valueFrom:
                configMapKeyRef:
                  key: tracer.host
                  name: tracing
            - name: METRICS_PUSH_URL
              valueFrom:
                configMapKeyRef:
                  key: push.gateway.url
                  name: prometheus
            - name: HOMEHUB_URL
              valueFrom:
                secretKeyRef:
                  name: homehub
                  key: homehub.url
            readinessProbe:
              httpGet:
                path: /__/health
                port: 8081
              initialDelaySeconds: 5
          restartPolicy: OnFailure
