version: "3.3"
services:
  pihole:
    hostname: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/London'
    volumes:
      - pihole_data:/etc/pihole/
      - pihole_dnsmasq_data:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pihole.rule=Host(`pihole.localhost`)"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
        - "traefik.tcp.services.pihole.loadbalancer.server.port=53"
        - "traefik.udp.services.pihole.loadbalancer.server.port=53"
        - "traefik.udp.services.pihole.loadbalancer.server.port=67"
        - "traefik.http.routers.pihole.entrypoints=http"

volumes:
  pihole_data: {}
  pihole_dnsmasq_data: {}

networks:
  default:
    external:
      name: traefik_internal
