version: "3.3"
services:
  prometheus-exporter-speedtest:
    hostname: prometheus-exporter-speedtest
    container_name: prometheus-exporter-speedtest
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-speedtest", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-speedtest
    restart: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  prometheus-exporter-pihole:
    hostname: prometheus-exporter-pihole
    container_name: prometheus-exporter-pihole
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-pihole", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-pihole
    environment:
      PIHOLE_URL: http://pihole
    restart: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  prometheus-exporter-weather:
    hostname: prometheus-exporter-weather
    container_name: prometheus-exporter-weather
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-weather", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-weather
    environment:
      API_KEY: ${WEATHER_API_KEY}
      LOCATION: ${WEATHER_LOCATION}
    restart: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  prometheus-exporter-coronavirus:
    hostname: prometheus-exporter-coronavirus
    container_name: prometheus-exporter-coronavirus
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-coronavirus", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-coronavirus
    restart: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  prometheus-exporter-homehub:
    hostname: prometheus-exporter-homehub
    container_name: prometheus-exporter-homehub
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-homehub", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-homehub
    environment:
      HOMEHUB_URL: ${HOMEHUB_URL}
    restart: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  prometheus-exporter-worldping:
    hostname: prometheus-exporter-worldping
    container_name: prometheus-exporter-worldping
    image: ghcr.io/davidsbond/homelab
    environment:
      PRIVILEGED: "true"
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-worldping", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-worldping
    restart: on-failure
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
networks:
  default:
    external:
      name: traefik_internal
