version: "3.3"
services:
  prometheus-exporter-speedtest:
    hostname: prometheus-exporter-speedtest
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-speedtest", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-speedtest

  prometheus-exporter-pihole:
    hostname: prometheus-exporter-pihole
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-pihole", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-pihole
    environment:
      PIHOLE_URL: http://pihole

  prometheus-exporter-weather:
    hostname: prometheus-exporter-weather
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-weather", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-weather
    env_file:
      - .env

  prometheus-exporter-coronavirus:
    hostname: prometheus-exporter-coronavirus
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-coronavirus", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-coronavirus

  prometheus-exporter-homehub:
    hostname: prometheus-exporter-homehub
    image: ghcr.io/davidsbond/homelab:latest
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-homehub", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-homehub
    env_file:
      - .env

  prometheus-exporter-worldping:
    hostname: prometheus-exporter-worldping
    image: ghcr.io/davidsbond/homelab:latest
    environment:
      PRIVILEGED: "true"
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-worldping", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-worldping

networks:
  default:
    external:
      name: traefik_internal
