apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus-exporters
#  - home-assistant
#  - deluge

secretGenerator:
  - name: registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=secrets/registry
