apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab

resources:
  - namespace.yaml
  - prometheus-exporters

secretGenerator:
  - name: registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=secrets/registry
