apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter-pihole
  labels:
    app: prometheus-exporter-pihole
spec:
  selector:
    matchLabels:
      app: prometheus-exporter-pihole
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /__/metrics
        prometheus.io/port: '8081'
      labels:
        app: prometheus-exporter-pihole
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - image: ghcr.io/davidsbond/homelab:latest
        name: prometheus-exporter-pihole
        command:
        - /bin/prometheus-exporter-pihole
        env:
        - name: PIHOLE_URL
          value: http://pihole.utilities.svc.cluster.local:8000
        readinessProbe:
          httpGet:
            path: /__/health
            port: 8081
          initialDelaySeconds: 5
