apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utilities

resources:
- namespace.yaml
- home-assistant
- pihole
- deluge
- bitwarden

configMapGenerator:
- name: tracing
  envs:
  - config/tracing

patchesStrategicMerge:
  - overlays/bitwarden.yaml
  - overlays/home-assistant.yaml
  - overlays/pihole.yaml

secretGenerator:
- name: pihole
  envs:
  - secrets/pihole
- name: bitwarden
  type: kubernetes.io/tls
  files:
  - secrets/tls.crt
  - secrets/tls.key
- name: minio
  envs:
  - secrets/minio
- name: registry
  type: kubernetes.io/dockerconfigjson
  files:
  - .dockerconfigjson=secrets/registry
