apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: query-http
      port: 16686
      protocol: TCP
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
    - name: agent-compact
      port: 6831
      protocol: UDP
    - name: agent-binary
      port: 6832
      protocol: UDP
    - name: agent-configs
      port: 5778
      protocol: TCP
  selector:
    app: jaeger
