global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets:
          - traefik:8080

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node-exporter
    dns_sd_configs:
      - names:
          - tasks.node-exporter
        type: A
        port: 9100

  - job_name: cadvisor
    dns_sd_configs:
      - names:
          - tasks.cadvisor
        type: A
        port: 8080

  - job_name: jaeger
    metrics_path: /metrics
    static_configs:
      - targets:
          - jaeger:14269

#  - job_name: exporters
#    metrics_path: /__/metrics
#    static_configs:
#      - targets:
#          - prometheus-exporter-speedtest:8081
#          - prometheus-exporter-pihole:8081
#          - prometheus-exporter-weather:8081
#          - prometheus-exporter-coronavirus:8081
#          - prometheus-exporter-homehub:8081
#          - prometheus-exporter-worldping:8081
