apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      imagePullSecrets:
        - name: registry
      containers:
      - image: homeassistant/home-assistant:latest
        name: home-assistant
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 120
        volumeMounts:
        - name: home-assistant
          mountPath: /config
        - name: home-assistant-config
          mountPath: /config
        - name: home-assistant-secret
          mountPath: /config
      # Volume backup has to be inline due to kustomize bug:
      # https://github.com/kubernetes-sigs/kustomize/issues/3117
      - image: ghcr.io/davidsbond/homelab:latest
        name: volume-backup
        command:
          - /bin/volume-backup
        env:
          - name: BUCKET_DSN
            value: s3://volumes?endpoint=minio.storage.svc.cluster.local:9000&region=none&s3ForcePathStyle=true&disableSSL=true
          - name: BUCKET_DIR
            value: home-assistant
          - name: VOLUME_DIR
            value: /data
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: minio.access_key
                name: minio
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: minio.secret_key
                name: minio
          - name: TRACER_DISABLED
            value: 'true'
        volumeMounts:
          - mountPath: /data
            name: home-assistant
      volumes:
      - name: home-assistant-config
        configMap:
          name: home-assistant
      - name: home-assistant-secret
        secret:
          secretName: home-assistant
      - name: home-assistant
        persistentVolumeClaim:
          claimName: home-assistant
