apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prometheus-exporter-speedtest
  labels:
    app: prometheus-exporter-speedtest
spec:
  schedule: 0 */1 * * *
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: registry
          containers:
          - image: ghcr.io/davidsbond/homelab:latest
            name: prometheus-exporter-speedtest
            command:
            - /bin/prometheus-exporter-speedtest
            env:
            - name: TRACER_HOST
              valueFrom:
                configMapKeyRef:
                  key: tracer.host
                  name: tracing
            - name: METRICS_PUSH_URL
              valueFrom:
                configMapKeyRef:
                  key: push.gateway.url
                  name: prometheus
            readinessProbe:
              httpGet:
                path: /__/health
                port: 8081
              initialDelaySeconds: 5
          restartPolicy: OnFailure
