apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter-weather
  labels:
    app: prometheus-exporter-weather
spec:
  selector:
    matchLabels:
      app: prometheus-exporter-weather
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /__/metrics
        prometheus.io/port: '8081'
      labels:
        app: prometheus-exporter-weather
    spec:
      imagePullSecrets:
      - name: registry
      containers:
      - image: ghcr.io/davidsbond/homelab:latest
        name: prometheus-exporter-weather
        command:
        - /bin/prometheus-exporter-weather
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: weather
              key: weather.api.key
        - name: LOCATION
          valueFrom:
            secretKeyRef:
              name: weather
              key: weather.location
        readinessProbe:
          httpGet:
            path: /__/health
            port: 8081
          initialDelaySeconds: 5
