version: "3.3"
services:
  prometheus-exporter-speedtest:
    hostname: prometheus-exporter-speedtest
    container_name: prometheus-exporter-speedtest
    image: prometheus-exporter-speedtest:latest
    build:
      dockerfile: Dockerfile
      context: ../..
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-speedtest", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-speedtest
    restart: on-failure

  prometheus-exporter-pihole:
    hostname: prometheus-exporter-pihole
    container_name: prometheus-exporter-pihole
    image: prometheus-exporter-pihole:latest
    build:
      dockerfile: Dockerfile
      context: ../..
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-pihole", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-pihole
    environment:
      PIHOLE_URL: http://pihole
    restart: on-failure

  prometheus-exporter-weather:
    hostname: prometheus-exporter-weather
    container_name: prometheus-exporter-weather
    image: prometheus-exporter-weather:latest
    build:
      dockerfile: Dockerfile
      context: ../..
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-weather", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-weather
    environment:
      API_KEY: ${WEATHER_API_KEY}
      LOCATION: ${WEATHER_LOCATION}
    restart: on-failure

  prometheus-exporter-coronavirus:
    hostname: prometheus-exporter-coronavirus
    container_name: prometheus-exporter-coronavirus
    image: prometheus-exporter-coronavirus:latest
    build:
      dockerfile: Dockerfile
      context: ../..
    healthcheck:
      test: [ "CMD", "/bin/prometheus-exporter-coronavirus", "check" ]
      interval: 60s
      timeout: 60s
      retries: 3
    command: /bin/prometheus-exporter-coronavirus
    restart: on-failure

networks:
  default:
    external:
      name: traefik_internal
