version: "3.3"
services:
  prometheus-exporter-speedtest:
    hostname: prometheus-exporter-speedtest
    container_name: prometheus-exporter-speedtest
    build:
      dockerfile: Dockerfile
      context: ../..
    command: /bin/prometheus-exporter-speedtest
    restart: on-failure

  prometheus-exporter-pihole:
    hostname: prometheus-exporter-pihole
    container_name: prometheus-exporter-pihole
    build:
      dockerfile: Dockerfile
      context: ../..
    command: /bin/prometheus-exporter-pihole
    environment:
      PIHOLE_URL: http://pihole
    restart: on-failure

  prometheus-exporter-weather:
    hostname: prometheus-exporter-weather
    container_name: prometheus-exporter-weather
    build:
      dockerfile: Dockerfile
      context: ../..
    command: /bin/prometheus-exporter-weather
    environment:
      API_KEY: ${WEATHER_API_KEY}
      LOCATION: ${WEATHER_LOCATION}
    restart: on-failure

networks:
  default:
    external:
      name: traefik_internal
