name: Docker
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  # Job that builds the docker image
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install tools
        run: |
          echo "::add-path::${HOME}/go/bin"
      - name: Build binaries
        run: make
      - name: Build docker image
        env:
          GITHUB_TOKEN: ${{ secrets.HOMELAB_GITHUB_TOKEN }}
        run: make PUSH=true docker
